/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wm/users/by-telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup user by Telegram ID or username
         * @description Fast path used on every incoming Telegram message. Wave Chat caches
         *     the response for `WAVE_CONNECT_CACHE_TTL_MS` (default 10 min).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated extra layers to load. */
                    include?: components["parameters"]["IncludeQuery"];
                    telegramId?: string;
                    username?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        /** Get user by Wave Match ID */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated extra layers to load. */
                    include?: components["parameters"]["IncludeQuery"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update soft profile fields
         * @description Optimistic concurrency: client MUST send `If-Match` with the ETag from
         *     a recent `GET`. On 412 the client should refetch and retry.
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "If-Match": string;
                };
                path: {
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        profile?: components["schemas"]["UserProfile"];
                        gender?: components["schemas"]["Gender"];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok: boolean;
                            updatedFields: string[];
                            etag: string;
                        };
                    };
                };
                412: components["responses"]["PreconditionFailed"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/wm/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (filterable)
         * @description Used by Wave Chat for broadcast-audience selection.
         */
        get: {
            parameters: {
                query?: {
                    subscriptionTier?: components["schemas"]["SubscriptionTier"];
                    subscriptionStatus?: components["schemas"]["SubscriptionStatus"];
                    clubSlug?: string;
                    marketingOptIn?: boolean;
                    lastActiveAfter?: string;
                    lastActiveBefore?: string;
                    hasEmail?: boolean;
                    hasTelegram?: boolean;
                    locale?: string;
                    minProfileCompleteness?: number;
                    cursor?: string;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["User"][];
                            cursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/users/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        /** List CRM notes for a user */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    type?: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrmNote"][];
                    };
                };
            };
        };
        put?: never;
        /** Append a CRM note */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CrmNoteCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrmNote"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active webhook subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookSubscription"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a webhook subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookSubscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/webhooks/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/wm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a Wave Match webhook event
         * @description Wave Match POSTs here for each subscribed event. Signed via HMAC-SHA256.
         *
         *     ### HMAC payload format
         *     ```
         *     message = `${X-WC-Timestamp}.${rawBody}`
         *     signature = sha256_hex(secret, message)
         *     header X-WC-Signature: sha256=<signature>
         *     ```
         *
         *     ### Rules
         *     - `X-WC-Timestamp` is **Unix epoch seconds** (NOT milliseconds).
         *     - Replay window: 300 seconds (configurable via `WAVE_CONNECT_WEBHOOK_REPLAY_WINDOW`).
         *     - Idempotency: receiver dedupes by `X-WC-Event-Id`.
         *     - Receiver responds with **200 OK** within ≤ 5 sec on success.
         *     - On any other status, sender retries: 1m → 5m → 30m → 2h → 6h → 24h, then dead-lettered.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-WC-Signature": string;
                    "X-WC-Timestamp": number;
                    "X-WC-Event-Id": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookEvent"];
                };
            };
            responses: {
                /** @description Accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok?: boolean;
                        };
                    };
                };
                /** @description Signature invalid / timestamp out of window */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example invalid signature */
                            error?: string;
                            /** @example timestamp skew 320s > 300s */
                            reason?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Gender: "MALE" | "FEMALE" | "UNKNOWN";
        /** @enum {string} */
        SubscriptionTier: "FREE" | "PRO" | "PREMIUM";
        /** @enum {string} */
        SubscriptionStatus: "ACTIVE" | "PAUSED" | "CANCELLED";
        /** @enum {string} */
        Locale: "ru" | "en";
        /** @enum {string} */
        CrmNoteType: "ai_dialog" | "ai_qualification_done" | "ai_match_proposed" | "ai_match_accepted" | "ai_match_rejected" | "ai_churn_signal" | "manual";
        UserProfile: {
            city?: string | null;
            /** @description Sphere of activity */
            activity?: string | null;
            businessCard?: string | null;
            bestClients?: string | null;
            requests?: string | null;
            hobbies?: string | null;
            currentIncome?: string | null;
            desiredIncome?: string | null;
            networkingGoal?: string | null;
            tags?: string[];
        };
        Subscription: {
            tier?: components["schemas"]["SubscriptionTier"];
            status?: components["schemas"]["SubscriptionStatus"];
            /** Format: date-time */
            currentPeriodStart?: string;
            /** Format: date-time */
            currentPeriodEnd?: string;
            marketingOptIn?: boolean;
        };
        ClubMembership: {
            /** @example b2b-pro */
            slug?: string;
            /** Format: date-time */
            joinedAt?: string;
            /** @enum {string} */
            role?: "MEMBER" | "MODERATOR" | "ADMIN";
        };
        Stats: {
            /** @example 47800 */
            lifetimeValue?: number;
            /** @example 12 */
            matchesCount?: number;
            /** Format: date-time */
            lastMatchAt?: string | null;
        };
        User: {
            /** @example wm_user_a1b2c3 */
            id: string;
            /** @example 123456789 */
            telegramId: string;
            /** @example ivan_petrov */
            username?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            gender?: components["schemas"]["Gender"];
            /** Format: phone */
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            locale?: components["schemas"]["Locale"];
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            lastActiveAt?: string | null;
            /** @example W/"42-abc123" */
            etag: string;
            profile?: components["schemas"]["UserProfile"];
            clubs?: components["schemas"]["ClubMembership"][];
            subscription?: components["schemas"]["Subscription"];
            stats?: components["schemas"]["Stats"];
        };
        CrmNoteCreate: {
            type: components["schemas"]["CrmNoteType"];
            summary: string;
            tags?: string[];
            linkedDialogId?: string;
        };
        CrmNote: components["schemas"]["CrmNoteCreate"] & {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Service-account or human user ID */
            authorId: string;
        };
        /** @enum {string} */
        WebhookEventName: "user.created" | "user.updated" | "profile.updated" | "club.joined" | "club.left" | "subscription.changed";
        WebhookSubscriptionCreate: {
            /**
             * Format: uri
             * @example https://aiass-production.up.railway.app/webhooks/wm
             */
            url: string;
            events: components["schemas"]["WebhookEventName"][];
            /** @description HMAC secret used to sign deliveries. */
            secret: string;
        };
        WebhookSubscription: components["schemas"]["WebhookSubscriptionCreate"] & {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @default 0 */
            failureCount: number;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            /** @description Never returned in responses; encrypted at rest. */
            secret?: string;
        };
        WebhookEventBase: {
            /** @example evt_a1b2c3 */
            eventId: string;
            event: components["schemas"]["WebhookEventName"];
            /** Format: date-time */
            occurredAt: string;
        };
        WebhookEvent: components["schemas"]["WebhookEvent_UserCreated"] | components["schemas"]["WebhookEvent_UserUpdated"] | components["schemas"]["WebhookEvent_ProfileUpdated"] | components["schemas"]["WebhookEvent_ClubJoined"] | components["schemas"]["WebhookEvent_ClubLeft"] | components["schemas"]["WebhookEvent_SubscriptionChanged"];
        WebhookEvent_UserCreated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "user.created";
            data?: {
                userId: string;
                telegramId?: string | null;
                username?: string | null;
                firstName?: string | null;
                locale?: components["schemas"]["Locale"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "user.created";
        };
        WebhookEvent_UserUpdated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "user.updated";
            data?: {
                userId: string;
                telegramId?: string | null;
                changedFields?: string[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "user.updated";
        };
        WebhookEvent_ProfileUpdated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "profile.updated";
            data?: {
                userId: string;
                telegramId?: string | null;
                fields?: components["schemas"]["UserProfile"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "profile.updated";
        };
        WebhookEvent_ClubJoined: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "club.joined";
            data?: {
                userId: string;
                telegramId?: string | null;
                clubSlug: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "club.joined";
        };
        WebhookEvent_ClubLeft: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "club.left";
            data?: {
                userId: string;
                clubSlug: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "club.left";
        };
        WebhookEvent_SubscriptionChanged: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "subscription.changed";
            data?: {
                userId: string;
                telegramId?: string | null;
                oldTier: components["schemas"]["SubscriptionTier"];
                newTier: components["schemas"]["SubscriptionTier"];
                status: components["schemas"]["SubscriptionStatus"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "subscription.changed";
        };
    };
    responses: {
        /** @description Missing or invalid Bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example unauthorized */
                    error?: string;
                };
            };
        };
        /** @description Entity not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example not_found */
                    error?: string;
                };
            };
        };
        /** @description ETag in If-Match did not match current resource version */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example etag_mismatch */
                    error?: string;
                };
            };
        };
        /** @description Request body validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example invalid_input */
                    error?: string;
                    details?: {
                        field?: string;
                        message?: string;
                    }[];
                };
            };
        };
    };
    parameters: {
        UserIdPath: string;
        /** @description Comma-separated extra layers to load. */
        IncludeQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
