/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/wm/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either UUID or `tg:<telegramId>` */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        /**
         * Get user by ID (UUID or `tg:<telegramId>`)
         * @description The path supports two id forms:
         *     - **`<uuid>`** — Wave Match internal user UUID
         *     - **`tg:<telegramId>`** — lookup by Telegram ID (used by Wave Chat on every
         *       incoming TG message, cached for 10 minutes by default)
         *
         *     Layers in `include` are additive. Without `include`, only base User fields
         *     are returned (no `profile`, `clubs`, `stats`).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated extra layers: `profile`, `clubs`, `stats` */
                    include?: components["parameters"]["IncludeQuery"];
                };
                header?: never;
                path: {
                    /** @description Either UUID or `tg:<telegramId>` */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        /** @description Strong ETag, format `"v{version}-{unix_seconds}"`. Echo back as `If-Match`. */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update writable user fields
         * @description ## Writable fields
         *     Only the keys listed under `WritableUserFields` are accepted. Any other
         *     key (including `profile.*`, `gender`, `subscription`) returns
         *     `400 readonly_field` with `{error, fields, allowedFields}`.
         *
         *     ## Concurrency
         *     `If-Match` is **optional** server-side but **strongly recommended**.
         *     - Without `If-Match`: update proceeds without version check.
         *     - With matching `If-Match`: update applies, fresh ETag returned.
         *     - With stale `If-Match`: `412 precondition_failed` with `{error, current: User}`.
         *
         *     ## Profile fields not modeled here
         *     Profile fields (`city`, `activity`, `businessCard`, `bestClients`,
         *     `requests`, `currentIncome`, `desiredIncome`, `networkingGoal`) **do not
         *     exist** in Wave Match. Wave Chat keeps them in its own DB.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match"?: string;
                };
                path: {
                    /** @description Either UUID or `tg:<telegramId>` */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WritableUserFields"];
                };
            };
            responses: {
                /** @description Updated. Body is the full User object; new ETag in header. */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Readonly field or invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError400"];
                    };
                };
                /** @description ETag mismatch (only when `If-Match` was sent and is stale) */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example precondition_failed */
                            error: string;
                            current: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/wm/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (filterable, cursor-paginated)
         * @description Used by Wave Chat for broadcast-audience selection.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Opaque base64url cursor from previous `nextCursor` */
                    cursor?: string;
                    updatedSince?: string;
                    /** @description Comma-separated; values from SubscriptionTier */
                    subscriptionTier?: string;
                    clubSlug?: string;
                    marketingOptIn?: boolean;
                    lastActiveBefore?: string;
                    lastActiveAfter?: string;
                    hasEmail?: boolean;
                    locale?: string;
                    /** @description Include `total` in response. Off by default to keep listing fast. */
                    withTotal?: "1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of users (slim shape) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["UserListItem"][];
                            nextCursor?: string | null;
                            /** @description Only present when `withTotal=1` was passed. */
                            total?: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/users/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either UUID or `tg:<telegramId>` */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        /** List CRM notes for a user */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Filter by single CrmNoteKind (not csv). */
                    kind?: components["schemas"]["CrmNoteKind"];
                };
                header?: never;
                path: {
                    /** @description Either UUID or `tg:<telegramId>` */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrmNote"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Append a CRM note
         * @description ## Wave Chat-specific note classification
         *     Wave Match has 6 note kinds. Wave Chat's domain events
         *     (`ai_qualification_done`, `ai_match_proposed`, `ai_churn_signal`, ...)
         *     are stored as `kind: "system"` with the AI label embedded into `body`
         *     and mirrored in `tags`. Example:
         *     ```json
         *     {
         *       "kind": "system",
         *       "body": "[ai_qualification_done] User passed qualification: maker, B2B SaaS",
         *       "tags": ["ai", "qualification"],
         *       "authorEmail": "wave-chat@aiass.app"
         *     }
         *     ```
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Either UUID or `tg:<telegramId>` */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CrmNoteCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrmNote"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError400"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active webhook subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookSubscription"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a webhook subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookSubscriptionCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookSubscription"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wm/webhooks/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subscriptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/wm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a Wave Match webhook event
         * @description Wave Match POSTs here for each subscribed event. Signed via HMAC-SHA256.
         *
         *     ### HMAC payload format
         *     ```
         *     message   = `${X-WC-Timestamp}.${rawBody}`
         *     signature = sha256_hex(WAVE_CONNECT_WEBHOOK_SECRET, message)
         *     header    X-WC-Signature: sha256=<signature>
         *     ```
         *
         *     ### Rules
         *     - `X-WC-Timestamp` is **Unix epoch seconds**.
         *     - Replay window: 300s (configurable via `WAVE_CONNECT_WEBHOOK_REPLAY_WINDOW`).
         *     - Idempotency: receiver dedupes by `X-WC-Delivery` header (UUID).
         *     - Receiver responds with **200 OK** within ≤ 5 sec on success.
         *     - On any other status, sender retries: 1m → 5m → 30m → 2h → 6h → 24h, then dead.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-WC-Signature": string;
                    "X-WC-Timestamp": number;
                    "X-WC-Delivery": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookEvent"];
                };
            };
            responses: {
                /** @description Accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            ok?: boolean;
                        };
                    };
                };
                /** @description Signature invalid / timestamp out of window */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example invalid signature */
                            error?: string;
                            reason?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SubscriptionTier: "FREE" | "PLUS" | "PREMIUM" | "PARTNER";
        /** @enum {string} */
        AuthProvider: "telegram" | "google" | "email" | "both";
        /** @enum {string} */
        NotifPrefs: "all" | "weekly" | "off";
        /**
         * @description Gender stored on Profile (not on User)
         * @enum {string}
         */
        Gender: "M" | "F" | "Other";
        /** @enum {string} */
        ClubRole: "member" | "admin";
        /** @enum {string} */
        CrmNoteKind: "call" | "email" | "meeting" | "note" | "status" | "system";
        ApiError400: {
            /**
             * @description e.g. `readonly_field`, `invalid_kind`, `invalid_body`, `invalid_input`
             * @example readonly_field
             */
            error: string;
            /** @description Offending fields (when `error=readonly_field`) */
            fields?: string[];
            /** @description Set of fields the endpoint accepts (when `error=readonly_field`) */
            allowedFields?: string[];
        };
        Profile: {
            role?: string | null;
            industry?: string | null;
            location?: string | null;
            company?: string | null;
            gender?: components["schemas"]["Gender"];
            tags?: string[];
            skills?: string[];
            hobbies?: string[];
            completion?: number;
        };
        Subscription: {
            tier?: components["schemas"]["SubscriptionTier"];
            /** Format: date-time */
            renewsAt?: string | null;
        };
        Balances: {
            usd?: number;
            tokens?: number;
            matchCredits?: number;
        };
        UserClubMembership: {
            /** @example b2b-pro */
            slug?: string;
            clubName?: string;
            /** Format: date-time */
            joinedAt?: string;
            role?: components["schemas"]["ClubRole"];
        };
        UserStats: {
            matchesCount?: number;
            connectionsCount?: number;
            /** Format: date-time */
            lastMatchAt?: string | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @description BigInt as string */
            telegramId?: string | null;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            firstName: string;
            lastName?: string | null;
            username?: string | null;
            /** Format: uri */
            photoUrl?: string | null;
            authProvider: components["schemas"]["AuthProvider"];
            /** @description Free string (e.g. `ru`, `en-US`). NOT an enum. */
            locale?: string | null;
            notifPrefs?: components["schemas"]["NotifPrefs"];
            marketingOptIn?: boolean;
            /** Format: date-time */
            marketingOptInUpdatedAt?: string | null;
            crmTags?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastActiveAt?: string;
            subscription?: components["schemas"]["Subscription"];
            balances?: components["schemas"]["Balances"];
            rating?: number;
            streakCount?: number;
            profile?: components["schemas"]["Profile"];
            clubs?: components["schemas"]["UserClubMembership"][];
            stats?: components["schemas"]["UserStats"];
        };
        UserListItem: {
            /** Format: uuid */
            id: string;
            telegramId?: string | null;
            email?: string | null;
            phone?: string | null;
            firstName: string;
            lastName?: string | null;
            locale?: string | null;
            subscriptionTier?: components["schemas"]["SubscriptionTier"];
            marketingOptIn?: boolean;
            crmTags?: string[];
            /** Format: date-time */
            lastActiveAt?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WritableUserFields: {
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            firstName?: string;
            lastName?: string | null;
            notifPrefs?: components["schemas"]["NotifPrefs"];
            marketingOptIn?: boolean;
            /** Format: date-time */
            marketingOptInUpdatedAt?: string;
            crmTags?: string[];
            locale?: string;
        };
        CrmNoteCreate: {
            kind?: components["schemas"]["CrmNoteKind"];
            body: string;
            /** Format: email */
            authorEmail?: string;
            /** @default false */
            pinned: boolean;
            tags?: string[];
        };
        CrmNote: components["schemas"]["CrmNoteCreate"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            authorId?: string | null;
        };
        /** @enum {string} */
        WebhookEventName: "user.created" | "user.updated" | "profile.updated" | "club.joined" | "club.left" | "subscription.changed";
        WebhookSubscriptionCreate: {
            /**
             * Format: uri
             * @example https://aiass-production.up.railway.app/webhooks/wm
             */
            url: string;
            events: components["schemas"]["WebhookEventName"][];
            /** @description HMAC secret used to sign deliveries. */
            secret: string;
        };
        WebhookSubscription: components["schemas"]["WebhookSubscriptionCreate"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** @default 0 */
            failureCount: number;
            /** Format: date-time */
            lastSuccessAt?: string | null;
            /** @description Never returned in responses; encryption-at-rest planned. */
            secret?: string;
        };
        WebhookEventBase: {
            event: components["schemas"]["WebhookEventName"];
            /** Format: uuid */
            deliveryId: string;
            /** Format: date-time */
            createdAt: string;
        };
        WebhookEvent: components["schemas"]["WebhookEvent_UserCreated"] | components["schemas"]["WebhookEvent_UserUpdated"] | components["schemas"]["WebhookEvent_ProfileUpdated"] | components["schemas"]["WebhookEvent_ClubJoined"] | components["schemas"]["WebhookEvent_ClubLeft"] | components["schemas"]["WebhookEvent_SubscriptionChanged"];
        WebhookEvent_UserCreated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "user.created";
            data: {
                user: components["schemas"]["User"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "user.created";
        };
        WebhookEvent_UserUpdated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "user.updated";
            data: {
                user: components["schemas"]["User"];
                changedFields?: string[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "user.updated";
        };
        WebhookEvent_ProfileUpdated: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "profile.updated";
            data: {
                /** Format: uuid */
                userId: string;
                profile: components["schemas"]["Profile"];
                /** @description true on first profile creation; absent on edits. */
                isFirstTime?: boolean;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "profile.updated";
        };
        WebhookEvent_ClubJoined: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "club.joined";
            data: {
                /** Format: uuid */
                userId: string;
                clubSlug: string;
                clubName?: string;
                role?: components["schemas"]["ClubRole"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "club.joined";
        };
        WebhookEvent_ClubLeft: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "club.left";
            data?: {
                /** Format: uuid */
                userId: string;
                clubSlug: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "club.left";
        };
        WebhookEvent_SubscriptionChanged: components["schemas"]["WebhookEventBase"] & {
            /** @enum {string} */
            event?: "subscription.changed";
            data?: {
                /** Format: uuid */
                userId: string;
                from: components["schemas"]["SubscriptionTier"];
                to: components["schemas"]["SubscriptionTier"];
                /** Format: date-time */
                effectiveAt: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "subscription.changed";
        };
    };
    responses: {
        /** @description Missing or invalid Bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example unauthorized */
                    error?: string;
                };
            };
        };
        /** @description Entity not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example not_found */
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Either UUID or `tg:<telegramId>` */
        UserIdPath: string;
        /** @description Comma-separated extra layers: `profile`, `clubs`, `stats` */
        IncludeQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
